### ISSUE TITLE
portage.exception.PortageKeyError: 'dev-python/fonttools-3.44.0'

### ISSUE THREAD

**Issue by ernsteiswuerfel** [gentoo/tatt#63]
Happens when I tatt bug 694372 (https://bugs.gentoo.org/694372).

```
# tatt -b 694372
Bugnumber:  694372
Keywording bug detected.
Jobname: zopfli-694372
Found the following package atom : =app-arch/zopfli-1.0.2
Found the following package atom : =dev-python/fonttools-3.44.0
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/tatt", line 213, in <module>
    kw = port.aux_get(dep_getcpv(p.packageString()), ["KEYWORDS"])
  File "/usr/lib/python3.6/site-packages/portage/dbapi/porttree.py", line 614, in aux_get
    myrepo=myrepo, loop=loop))
  File "/usr/lib/python3.6/site-packages/portage/util/_eventloop/EventLoop.py", line 833, in run_until_complete
    return future.result()
portage.exception.PortageKeyError: 'dev-python/fonttools-3.44.0'
```

**Comment by ernsteiswuerfel** [comment]
Turned out that fonttools-3.44.0 simply was not in my local portage yet. Needed an emerge --sync first... d'oh.

Sorry for the noise!
