### ISSUE TITLE
problem with keywording bugs (ppc)

### ISSUE THREAD

**Issue by ernsteiswuerfel** [gentoo/tatt#65]
tatt seems to have problems with keywording bugs (e.g. bug 719694). Stabilization bugs (e.g. bug 711784) work fine.

```
# tatt -b 719694
Bugnumber:  719694
Keywording bug detected.
Jobname: argcomplete-719694
Found the following package atom : dev-python/argcomplete
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/tatt", line 213, in <module>
    kw = port.aux_get(dep_getcpv(p.packageString()), ["KEYWORDS"])
  File "/usr/lib/python3.6/site-packages/portage/dbapi/porttree.py", line 614, in aux_get
    myrepo=myrepo, loop=loop))
  File "/usr/lib/python3.6/site-packages/portage/dbapi/porttree.py", line 673, in async_aux_get
    myebuild, mylocation = self.findname2(mycpv, mytree)
  File "/usr/lib/python3.6/site-packages/portage/dbapi/porttree.py", line 484, in findname2
    raise InvalidPackageName(mycpv)
portage.exception.InvalidPackageName: dev-python/argcomplete
```

**Comment by leio** [comment]
It currently doesn't support package lists that lack version numbers in the package atoms. They aren't valid package atoms for it, and it doesn't go and fill them out for you (yet) based on what's latest.
stable-bot didn't support it either, so it's a new feature from nattka era now, which hasn't been added in tatt, at least in the version you are using (I haven't followed git and pull requests here)

**Comment by DerDakon** [comment]
It's not supported even in git.
