### ISSUE TITLE
tatt crashes when 'unmaskdir' config value is unset

### ISSUE THREAD

**Issue by ajakk** [gentoo/tatt#68]
Introduced in `a5f83728d12e841c67e9e264baa4d71d26aba0d4`. In previous versions tatt would give an error like:
```sh
tatt $ ./scripts/tatt -b723346
Bugnumber:  723346
Stabilization bug detected.
Jobname: cdrtools-723346
Found the following package atom : =app-cdr/cdrtools-3.02_alpha09-r2
Your unmaskfile was not found, I will create it as
/etc/portage/package.accept_keywords/archtest
Can not write to  /etc/portage/package.accept_keywords/archtest
Maybe you don't have permission or the location is invalid.
Is /etc/portage/package.accept_keywords a writeable directory?
Probably you want to configure a different unmaskfile
in your ~/.tatt.  Exiting
```

When the repository is at said commit:
```sh
tatt $ ./scripts/tatt -b723346
Bugnumber:  723346
Stabilization bug detected.
Jobname: cdrtools-723346
Found the following package atom : =app-cdr/cdrtools-3.02_alpha09-r2
Traceback (most recent call last):
  File "./scripts/tatt", line 242, in <module>
    unmaskname=config['unmaskdir']
  File "/usr/lib/python3.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'unmaskdir'
```

Note this isn't reproducable with the live ebuild, only when running from the source repository. Adding `unmaskdir` to `~/.tatt` fixes it.

**Comment by ajakk** [comment]
Oh, sorry, there's some confusion between the system version and local version.
